/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to CXX Translator
  File name: C:\DXEProjects\Tools\cyclonedds\build64\bin\Debug\IMUState.idl
  Source: IMUState.cpp
  Cyclone DDS: v0.11.0

*****************************************************************/
#include "IMUState.hpp"

#include <org/eclipse/cyclonedds/util/ostream_operators.hpp>

namespace unitree_go
{
    namespace msg
    {
        namespace dds_
        {
            std::ostream& operator<<(std::ostream& os, IMUState_ const& rhs)
            {
                (void)rhs;
                os << "[";
                os << "quaternion: " << rhs.quaternion();
                os << ", gyroscope: " << rhs.gyroscope();
                os << ", accelerometer: " << rhs.accelerometer();
                os << ", rpy: " << rhs.rpy();
                os << ", temperature: " << rhs.temperature();
                os << "]";
                return os;
            }

        } //namespace dds_

    } //namespace msg

} //namespace unitree_go

namespace org {
    namespace eclipse {
        namespace cyclonedds {
            namespace core {
                namespace cdr {

                    template<>
                    const propvec& get_type_props<::unitree_go::msg::dds_::IMUState_>() {
                        static std::mutex mtx;
                        static propvec props;
                        static std::atomic_bool initialized{ false };
                        key_endpoint keylist;
                        if (initialized.load(std::memory_order_relaxed))
                            return props;
                        std::lock_guard<std::mutex> lock(mtx);
                        if (initialized.load(std::memory_order_relaxed))
                            return props;
                        props.clear();

                        props.push_back(entity_properties_t(0, 0, false, bit_bound::bb_unset, extensibility::ext_final));  //root
                        props.push_back(entity_properties_t(1, 0, false, get_bit_bound<float>(), extensibility::ext_final, false));  //::quaternion
                        props.push_back(entity_properties_t(1, 1, false, get_bit_bound<float>(), extensibility::ext_final, false));  //::gyroscope
                        props.push_back(entity_properties_t(1, 2, false, get_bit_bound<float>(), extensibility::ext_final, false));  //::accelerometer
                        props.push_back(entity_properties_t(1, 3, false, get_bit_bound<float>(), extensibility::ext_final, false));  //::rpy
                        props.push_back(entity_properties_t(1, 4, false, get_bit_bound<uint8_t>(), extensibility::ext_final, false));  //::temperature

                        entity_properties_t::finish(props, keylist);
                        initialized.store(true, std::memory_order_release);
                        return props;
                    }

                } //namespace cdr
            } //namespace core
        } //namespace cyclonedds
    } //namespace eclipse
} //namespace org