/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to CXX Translator
  File name: C:\DXEProjects\Tools\cyclonedds\build64\bin\Debug\LowState.idl
  Source: LowState.cpp
  Cyclone DDS: v0.11.0

*****************************************************************/
#include "LowState.hpp"

#include <org/eclipse/cyclonedds/util/ostream_operators.hpp>

namespace unitree_go
{
    namespace msg
    {
        namespace dds_
        {
            std::ostream& operator<<(std::ostream& os, LowState_ const& rhs)
            {
                (void)rhs;
                os << "[";
                os << "head: " << rhs.head();
                os << ", level_flag: " << rhs.level_flag();
                os << ", frame_reserve: " << rhs.frame_reserve();
                os << ", sn: " << rhs.sn();
                os << ", version: " << rhs.version();
                os << ", bandwidth: " << rhs.bandwidth();
                os << ", imu_state: " << rhs.imu_state();
                os << ", motor_state: " << rhs.motor_state();
                os << ", bms_state: " << rhs.bms_state();
                os << ", foot_force: " << rhs.foot_force();
                os << ", foot_force_est: " << rhs.foot_force_est();
                os << ", tick: " << rhs.tick();
                os << ", wireless_remote: " << rhs.wireless_remote();
                os << ", bit_flag: " << rhs.bit_flag();
                os << ", adc_reel: " << rhs.adc_reel();
                os << ", temperature_ntc1: " << rhs.temperature_ntc1();
                os << ", temperature_ntc2: " << rhs.temperature_ntc2();
                os << ", power_v: " << rhs.power_v();
                os << ", power_a: " << rhs.power_a();
                os << ", fan_frequency: " << rhs.fan_frequency();
                os << ", reserve: " << rhs.reserve();
                os << ", crc: " << rhs.crc();
                os << "]";
                return os;
            }

        } //namespace dds_

    } //namespace msg

} //namespace unitree_go

namespace org {
    namespace eclipse {
        namespace cyclonedds {
            namespace core {
                namespace cdr {

                    template<>
                    const propvec& get_type_props<::unitree_go::msg::dds_::LowState_>() {
                        static std::mutex mtx;
                        static propvec props;
                        static std::atomic_bool initialized{ false };
                        key_endpoint keylist;
                        if (initialized.load(std::memory_order_relaxed))
                            return props;
                        std::lock_guard<std::mutex> lock(mtx);
                        if (initialized.load(std::memory_order_relaxed))
                            return props;
                        props.clear();

                        props.push_back(entity_properties_t(0, 0, false, bit_bound::bb_unset, extensibility::ext_final));  //root
                        props.push_back(entity_properties_t(1, 0, false, get_bit_bound<uint8_t>(), extensibility::ext_final, false));  //::head
                        props.push_back(entity_properties_t(1, 1, false, get_bit_bound<uint8_t>(), extensibility::ext_final, false));  //::level_flag
                        props.push_back(entity_properties_t(1, 2, false, get_bit_bound<uint8_t>(), extensibility::ext_final, false));  //::frame_reserve
                        props.push_back(entity_properties_t(1, 3, false, get_bit_bound<uint32_t>(), extensibility::ext_final, false));  //::sn
                        props.push_back(entity_properties_t(1, 4, false, get_bit_bound<uint32_t>(), extensibility::ext_final, false));  //::version
                        props.push_back(entity_properties_t(1, 5, false, get_bit_bound<uint16_t>(), extensibility::ext_final, false));  //::bandwidth
                        props.push_back(entity_properties_t(1, 6, false, get_bit_bound<::unitree_go::msg::dds_::IMUState_>(), extensibility::ext_final, false));  //::imu_state
                        entity_properties_t::append_struct_contents(props, get_type_props<::unitree_go::msg::dds_::IMUState_>());  //internal contents of ::imu_state
                        props.push_back(entity_properties_t(1, 7, false, get_bit_bound<::unitree_go::msg::dds_::MotorState_>(), extensibility::ext_final, false));  //::motor_state
                        entity_properties_t::append_struct_contents(props, get_type_props<::unitree_go::msg::dds_::MotorState_>());  //internal contents of ::motor_state
                        props.push_back(entity_properties_t(1, 8, false, get_bit_bound<::unitree_go::msg::dds_::BmsState_>(), extensibility::ext_final, false));  //::bms_state
                        entity_properties_t::append_struct_contents(props, get_type_props<::unitree_go::msg::dds_::BmsState_>());  //internal contents of ::bms_state
                        props.push_back(entity_properties_t(1, 9, false, get_bit_bound<int16_t>(), extensibility::ext_final, false));  //::foot_force
                        props.push_back(entity_properties_t(1, 10, false, get_bit_bound<int16_t>(), extensibility::ext_final, false));  //::foot_force_est
                        props.push_back(entity_properties_t(1, 11, false, get_bit_bound<uint32_t>(), extensibility::ext_final, false));  //::tick
                        props.push_back(entity_properties_t(1, 12, false, get_bit_bound<uint8_t>(), extensibility::ext_final, false));  //::wireless_remote
                        props.push_back(entity_properties_t(1, 13, false, get_bit_bound<uint8_t>(), extensibility::ext_final, false));  //::bit_flag
                        props.push_back(entity_properties_t(1, 14, false, get_bit_bound<float>(), extensibility::ext_final, false));  //::adc_reel
                        props.push_back(entity_properties_t(1, 15, false, get_bit_bound<uint8_t>(), extensibility::ext_final, false));  //::temperature_ntc1
                        props.push_back(entity_properties_t(1, 16, false, get_bit_bound<uint8_t>(), extensibility::ext_final, false));  //::temperature_ntc2
                        props.push_back(entity_properties_t(1, 17, false, get_bit_bound<float>(), extensibility::ext_final, false));  //::power_v
                        props.push_back(entity_properties_t(1, 18, false, get_bit_bound<float>(), extensibility::ext_final, false));  //::power_a
                        props.push_back(entity_properties_t(1, 19, false, get_bit_bound<uint16_t>(), extensibility::ext_final, false));  //::fan_frequency
                        props.push_back(entity_properties_t(1, 20, false, get_bit_bound<uint32_t>(), extensibility::ext_final, false));  //::reserve
                        props.push_back(entity_properties_t(1, 21, false, get_bit_bound<uint32_t>(), extensibility::ext_final, false));  //::crc

                        entity_properties_t::finish(props, keylist);
                        initialized.store(true, std::memory_order_release);
                        return props;
                    }

                } //namespace cdr
            } //namespace core
        } //namespace cyclonedds
    } //namespace eclipse
} //namespace org