/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to CXX Translator
  File name: C:\DXEProjects\Tools\cyclonedds\build64\bin\Debug\MotorState.idl
  Source: MotorState.cpp
  Cyclone DDS: v0.11.0

*****************************************************************/
#include "MotorState.hpp"

#include <org/eclipse/cyclonedds/util/ostream_operators.hpp>

namespace unitree_go
{
    namespace msg
    {
        namespace dds_
        {
            std::ostream& operator<<(std::ostream& os, MotorState_ const& rhs)
            {
                (void)rhs;
                os << "[";
                os << "mode: " << rhs.mode();
                os << ", q: " << rhs.q();
                os << ", dq: " << rhs.dq();
                os << ", ddq: " << rhs.ddq();
                os << ", tau_est: " << rhs.tau_est();
                os << ", q_raw: " << rhs.q_raw();
                os << ", dq_raw: " << rhs.dq_raw();
                os << ", ddq_raw: " << rhs.ddq_raw();
                os << ", temperature: " << rhs.temperature();
                os << ", lost: " << rhs.lost();
                os << ", reserve: " << rhs.reserve();
                os << "]";
                return os;
            }

        } //namespace dds_

    } //namespace msg

} //namespace unitree_go

namespace org {
    namespace eclipse {
        namespace cyclonedds {
            namespace core {
                namespace cdr {

                    template<>
                    const propvec& get_type_props<::unitree_go::msg::dds_::MotorState_>() {
                        static std::mutex mtx;
                        static propvec props;
                        static std::atomic_bool initialized{ false };
                        key_endpoint keylist;
                        if (initialized.load(std::memory_order_relaxed))
                            return props;
                        std::lock_guard<std::mutex> lock(mtx);
                        if (initialized.load(std::memory_order_relaxed))
                            return props;
                        props.clear();

                        props.push_back(entity_properties_t(0, 0, false, bit_bound::bb_unset, extensibility::ext_final));  //root
                        props.push_back(entity_properties_t(1, 0, false, get_bit_bound<uint8_t>(), extensibility::ext_final, false));  //::mode
                        props.push_back(entity_properties_t(1, 1, false, get_bit_bound<float>(), extensibility::ext_final, false));  //::q
                        props.push_back(entity_properties_t(1, 2, false, get_bit_bound<float>(), extensibility::ext_final, false));  //::dq
                        props.push_back(entity_properties_t(1, 3, false, get_bit_bound<float>(), extensibility::ext_final, false));  //::ddq
                        props.push_back(entity_properties_t(1, 4, false, get_bit_bound<float>(), extensibility::ext_final, false));  //::tau_est
                        props.push_back(entity_properties_t(1, 5, false, get_bit_bound<float>(), extensibility::ext_final, false));  //::q_raw
                        props.push_back(entity_properties_t(1, 6, false, get_bit_bound<float>(), extensibility::ext_final, false));  //::dq_raw
                        props.push_back(entity_properties_t(1, 7, false, get_bit_bound<float>(), extensibility::ext_final, false));  //::ddq_raw
                        props.push_back(entity_properties_t(1, 8, false, get_bit_bound<uint8_t>(), extensibility::ext_final, false));  //::temperature
                        props.push_back(entity_properties_t(1, 9, false, get_bit_bound<uint32_t>(), extensibility::ext_final, false));  //::lost
                        props.push_back(entity_properties_t(1, 10, false, get_bit_bound<uint32_t>(), extensibility::ext_final, false));  //::reserve

                        entity_properties_t::finish(props, keylist);
                        initialized.store(true, std::memory_order_release);
                        return props;
                    }

                } //namespace cdr
            } //namespace core
        } //namespace cyclonedds
    } //namespace eclipse
} //namespace org